- name: enable mongodb-org repository
  template: src=mongodb-org.repo.j2 dest=/etc/yum.repos.d/mongodb-org.repo

- name: yum install/uninstall packages
  yum: name={{ item.name }} state={{ item.state }}
  with_items: "{{ mongod_packages }}"

- name: create replicaSet initialization script
  template: src=replicaSetInit.js.j2 dest=/tmp/replicaSetInit.js

- name: format data volume(s)
  filesystem: fstype={{ item.value.fstype }} dev={{ item.value.device }}
  with_dict: "{{ mongod_volumes }}"

- name: mount data volume(s)
  mount:
    name: "{{ item.value.mount }}"
    src: "{{ item.value.device }}"
    state: mounted
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.mount_opts }}"
  with_dict: "{{ mongod_volumes }}"

- name: set permissions data volume(s)
  file: state=directory path={{ item.value.mount }} recurse=yes owner={{ mongod_user }} group={{ mongod_group }}
  with_dict: "{{ mongod_volumes }}"

- name: template mongod.conf
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify: restart-mongod

- name: service enable and start
  service: name=mongod state=started enabled=yes

# configure the replicaSet (if needed)
- name: check replicaSet status
  command: /usr/bin/mongo --quiet --eval 'printjson(rs.status().startupStatus === undefined)'
  register: mongo_result

- name: initialize replicaSet
  command: /usr/bin/mongo /tmp/replicaSetInit.js
  when: mongo_result.stdout == 'true'
